# Generated by Django 4.2.11 on 2026-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelpresence',
            options={'ordering': ['year', 'month', 'employee_code', 'employee_name']},
        ),
        migrations.CreateModel(
            name='PersonnelMasterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=100)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('hire_date', models.CharField(blank=True, default='', max_length=100)),
                ('termination_date', models.CharField(blank=True, default='', max_length=100)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('employment_status', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'maticna_knjiga',
                'unique_together': {('employee_code', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ActualBudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('department', models.CharField(max_length=255)),
                ('budget_value', models.CharField(blank=True, default='', max_length=100)),
                ('actual_value', models.CharField(blank=True, default='', max_length=100)),
                ('variance', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'actual_budget_data',
                'unique_together': {('month', 'year', 'department')},
            },
        ),
    ]
