# Generated by Django 4.2.11 on 2026-04-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel', '0002_alter_personnelpresence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelmasterrecord',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personnelmasterrecord',
            name='seniority_months',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
