# Generated by Django 4.2.11 on 2026-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel', '0003_personnelmasterrecord_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=100)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('actual_pos_after', models.CharField(blank=True, default='', max_length=255)),
                ('actual_pos_before', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'personnel_actual_data',
                'unique_together': {('employee_code', 'month', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='ActualBudgetData',
        ),
    ]
