# Generated by Django 4.2.11 on 2026-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel', '0004_replace_actualbudgetdata_with_personnelactualdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('site', models.CharField(choices=[('SUB', 'SUB'), ('KIK', 'KIK'), ('SEN', 'SEN')], max_length=3)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('budgeted_turnover_gap', models.DecimalField(blank=True, decimal_places=4, help_text='Npr. 0.33 za 33%', max_digits=6, null=True)),
                ('target', models.PositiveIntegerField(blank=True, help_text='Op. in line logging on iPad TARGET', null=True)),
            ],
            options={
                'db_table': 'budget_plan_data',
                'unique_together': {('month', 'year', 'site')},
            },
        ),
    ]
