# Generated by Django 4.2.11 on 2026-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=21)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FTP Settings',
            },
        ),
        migrations.CreateModel(
            name='ZucchettiCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=20)),
                ('card_code', models.CharField(max_length=30)),
                ('col3', models.CharField(blank=True, max_length=20)),
                ('emp_code', models.CharField(max_length=20)),
                ('col5', models.CharField(blank=True, max_length=20)),
                ('col6', models.CharField(blank=True, max_length=20)),
                ('col7', models.CharField(blank=True, max_length=20)),
                ('col8', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Zucchetti Card',
                'ordering': ['emp_code'],
            },
        ),
        migrations.CreateModel(
            name='ZucchettiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20)),
                ('plant', models.CharField(max_length=20)),
                ('employee', models.CharField(max_length=100)),
                ('t1', models.CharField(blank=True, max_length=20)),
                ('t2', models.CharField(blank=True, max_length=20)),
                ('t3', models.CharField(blank=True, max_length=20)),
                ('t4', models.CharField(blank=True, max_length=20)),
                ('t5', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Zucchetti User',
                'ordering': ['employee'],
            },
        ),
    ]
