# Generated by Django 4.2.11 on 2026-05-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zucchetti', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FTPSettings',
        ),
    ]
