# Generated by Django 4.2.11 on 2026-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zucchetti', '0002_delete_ftpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('activation_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('plant', models.CharField(max_length=10)),
                ('card_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Badge Record',
                'ordering': ['subject_code', 'activation_date'],
            },
        ),
    ]
