# Generated by Django 4.2.11 on 2026-05-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zucchetti', '0003_badgerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZucchettiCard',
        ),
    ]
