# Generated by Django 4.2.11 on 2026-05-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zucchetti', '0004_delete_zucchetticard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZucchettiUser',
        ),
    ]
