# Generated by Django 4.2.11 on 2026-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zucchetti', '0005_delete_zucchettiuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('plant', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['emp_code'],
            },
        ),
        migrations.CreateModel(
            name='PlantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=20)),
                ('terminal', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['plant'],
            },
        ),
    ]
