# Generated by Django 4.2.11 on 2026-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zucchetti', '0006_newrequest_plantsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZucchettiEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('card_code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['emp_code'],
            },
        ),
        migrations.DeleteModel(
            name='BadgeRecord',
        ),
    ]
